---

accounts:
  - username: test
    password: test
    permissions:
      collection-a: modify
      collection-b: read
      collection-c: read
      collection-xyz: some
  - username: admin
    password: admin
    is_admin: yes
