name: Check docstring coverage

on:
  - pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout head branch
      uses: actions/checkout@v3
      with:
        path: head
    - name: Checkout base branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.base_ref }}
        path: base
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install interrogate
      run: pip install -r head/requirements-interrogate.txt
    - name: Run interrogate on base branch for baseline
      run: echo "old_cov=$(echo $(head/.github/workflows/interrogate.sh base/opentaxii) - '0.1' | bc)" >> $GITHUB_ENV
    - name: Run interrogate on head branch to check coverage didn't drop
      run: interrogate --fail-under=${{ env.old_cov }} head/opentaxii
